name: CI/CD Pipeline

on:
  push:
    branches:
      - main    # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment in which your workflow runs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push my-app

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        ssh -i "path-to-your-ec2-key.pem" ec2-user@your-ec2-public-ip 'bash -s' < deploy.sh

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run integration tests
      run: |
        # Command to run your integration tests
        ./run-integration-tests.sh

  production:
    runs-on: ubuntu-latest

    needs: [deploy, test]   # Ensure tests pass before going to production

    steps:
    - name: Deploy to production
      run: |
        ssh -i "path-to-your-ec2-key.pem" ec2-user@your-ec2-public-ip 'bash -s' < production-deploy.sh
